---
- name: Install and Configure Apache
  hosts: webservers
  become: yes
  become_user: root

  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
      update_cache: yes
  - name: Enable service and start service
    service:
      name: apache2
      enabled: yes
      state: started
  - name: Remove the existing index
    file:
      path: /var/www/html/index.html
      state: absent
  - name: Create a new empty index
    file:
      path: /var/www/html/index.html
      state: touch
      owner: root
      group: root
      mode: 0755
  - name: Add content
    lineinfile:
      path: /var/www/html/index.html
      line: Hello Ansible World!
